export const LIMITS = Object.freeze({
  AUTH: {
    NAME_MAX_LENGTH: 100,
    EMAIL_MAX_LENGTH: 254,
    PASSWORD_MIN_LENGTH: 8,
    PASSWORD_MAX_LENGTH: 128,
  },

  VEHICLE: {
    REG_NUMBER_MAX_LENGTH: 20,
    MODEL_MAX_LENGTH: 100,
    LOCATION_MAX_LENGTH: 100,
    DAILY_RATE_MIN: 1,
    DAILY_RATE_MAX: 100000,
  },

  BOOKING: {
    MIN_RENTAL_DAYS: 1,
  },

  PAGINATION: {
    DEFAULT_PAGE_SIZE: 10,
    MAX_PAGE_SIZE: 50,
  },
});
